# Use the official Node.js image
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the application's port
EXPOSE 5000

# Start the application
CMD ["npm", "run", "dev"]


# FROM node:22-alpine

# WORKDIR /app

# COPY package*.json ./

# RUN npm ci --omit=dev

# COPY . .

# EXPOSE 5000

# CMD ["npm", "start"]